version: '3.8'

services:
  php-app-rmb:
    image: ${IMAGE_NAME}
    container_name: php-app-rmb
    networks:
      - app-network
      - pesantech-network

  nginx-app-rmb:
    image: nginx:alpine
    container_name: nginx-app-rmb
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/storage          # persist only storage
      - ./.env:/var/www/.env                # inject env file
    depends_on:
      - php-app-rmb
    networks:
      - app-network
      - pesantech-network
    ports:
      - "80:80"

networks:
  app-network:
    driver: bridge
  pesantech-network:
    external: true
