server {
    listen 80;
    server_name rmb.pesantech.web.id;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php-app-rmb:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|webp|woff2?|ttf|svg|eot)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    error_log  /var/log/nginx/rmb_error.log;
    access_log /var/log/nginx/rmb_access.log;
}
