server {
    listen 80;
    server_name spidest.pesantech.web.id spidest.com;

    root /app/public;  # Path to your Laravel app's 'public' directory
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ ^/(usr|var|etc|bin|lib) {
        deny all;
        return 403;
    }

    location ~ \.php$ {
        fastcgi_pass php-app-spidest:9000;  # Use 'php-app' as the name of your PHP-FPM container.
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    error_log /var/log/nginx/spidest_error.log;
    access_log /var/log/nginx/spidest_access.log;
}
